/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;
import java.sql.*;

/**
 *
 * @author anike
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_FName = new javax.swing.JTextField();
        txt_LName = new javax.swing.JTextField();
        btn_retrieve = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_inst_name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_result_student_type = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_result_milestones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        txt_FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FNameActionPerformed(evt);
            }
        });

        btn_retrieve.setText("Retrieve");
        btn_retrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retrieveActionPerformed(evt);
            }
        });

        jLabel3.setText("Instructor Name:");

        jLabel4.setText("Student Type :");

        jLabel5.setText("Milestone Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_retrieve)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_FName, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(txt_LName))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_inst_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_result_student_type, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 358, Short.MAX_VALUE))
                    .addComponent(lbl_result_milestones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(lbl_inst_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(lbl_result_student_type, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btn_retrieve))
                            .addComponent(lbl_result_milestones, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FNameActionPerformed

    private void btn_retrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retrieveActionPerformed
        // TODO add your handling code here:
        String Student_FName = txt_FName.getText();
        String Student_LName = txt_LName.getText();
        String result = "";
        //System.out.println("Printing info for "+ Student_FName + ", "+ Student_LName);
        
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/doctoral", "root", "password");
            //System.out.println("\nConnection Successful!");
            //Statement stmt = conn.createStatement();
            PreparedStatement s = conn.prepareStatement("select Instructor.FName, Instructor.LName from phd_student left join instructor on phd_student.Supervisor = instructor.InstructorId where phd_student.FName = ? and phd_student.LName = ?");
            s.setString(1, Student_FName);
            s.setString(2, Student_LName);
            ResultSet rs = s.executeQuery();
            while(rs.next()){
                String FName = rs.getString("FName");
                String LName = rs.getString("LName");
                lbl_inst_name.setText(FName+" "+LName);
                }
            
            PreparedStatement s2 = conn.prepareStatement("select phd_student.StudentId from studentgra left join phd_student on studentgra.StudentId = phd_student.StudentId where phd_student.FName = ? and phd_student.LName = ?;");
            s2.setString(1, Student_FName);
            s2.setString(2, Student_LName);
            ResultSet rs2 = s2.executeQuery();
            if(rs2.next()){
                //System.out.println(Student_FName + " " + Student_LName + " is GRA");
                lbl_result_student_type.setText("GRA");
                }
            
            else
            {
                PreparedStatement s3 = conn.prepareStatement("select phd_student.StudentId from studentgta left join phd_student on studentgta.StudentId = phd_student.StudentId where phd_student.FName = ? and phd_student.LName = ?;");
                s3.setString(1, Student_FName);
                s3.setString(2, Student_LName);
                ResultSet rs3 = s3.executeQuery();
                if(rs3.next()){
                    //System.out.println(Student_FName + " " + Student_LName + " is GTA");
                    lbl_result_student_type.setText("GTA");
                    }

                else
                {
                    PreparedStatement s4 = conn.prepareStatement("select phd_student.StudentId from studentscholarshipsupport left join phd_student on studentscholarshipsupport.StudentId = phd_student.StudentId where phd_student.FName = ? and phd_student.LName = ?;");
                    s4.setString(1, Student_FName);
                    s4.setString(2, Student_LName);
                    ResultSet rs4 = s4.executeQuery();
                    if(rs4.next()){
                        //System.out.println(Student_FName + " " + Student_LName + " is Scholarship Support");
                        lbl_result_student_type.setText("Scholarship Supported");
                        }

                    else
                    {
                        //System.out.println(Student_FName + " " + Student_LName + " is Self Support");
                        lbl_result_student_type.setText("Self Supported");
                    }
                }
            }
                    
            PreparedStatement s5 = conn.prepareStatement("select MName, PassDate from phd_student join milestonespassed on phd_student.StudentId = milestonespassed.StudentId join milestone on milestonespassed.MId = milestone.MId where phd_student.FName = ? and phd_student.LName = ?;");
            s5.setString(1, Student_FName);
            s5.setString(2, Student_LName);
            ResultSet rs5 = s5.executeQuery();
            while(rs5.next()){
                
                String MName = rs5.getString(1);
                String PassDate = rs5.getString(2);
                result = result + MName+" : "+PassDate + "<br/>";
                //System.out.println(result);
            }
            lbl_result_milestones.setText("<html>"+result+"</html>");
        
        }
        catch(Exception e){
            e.printStackTrace();
           }
        
    }//GEN-LAST:event_btn_retrieveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_retrieve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_inst_name;
    private javax.swing.JLabel lbl_result_milestones;
    private javax.swing.JLabel lbl_result_student_type;
    private javax.swing.JTextField txt_FName;
    private javax.swing.JTextField txt_LName;
    // End of variables declaration//GEN-END:variables
}
